id: A52CFCB03
title: Summary of Striking the Vital Point in Three Statements
type: translation
pechas:
- IBF3C3AEB
- IC335D281
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:42.791744
  last_modified_at: 2023-01-04 11:47:42.791749
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IBF3C3AEB/4DA7: D565
  IC335D281/8728: D565
